import axios from "axios"

// const PATCH_PRESENTATION_URL = “https://rhs-pivot-backend.herokuapp.com/api/presentations/{presentation_id}”;
// req.body = slides [
//     {slide_image_url: String,
//     slide_id: String,
//     }
// ]
// // PUT request: pivot question added/changed
// const PUT_PIVOT_URL = “https://rhs-pivot-backend.herokuapp.com/api/presentations/{presentation_id}/pivots/{slide_id}”;
// const GET_PIVOT_URL = “https://rhs-pivot-backend.herokuapp.com/api/presentations/{presentation_id}/pivots/”;

// presentationSchema = {
//     new mongoose.Schema({
//         presentation_id: String,
//         current_slide_index: Number,
//         slides : [
//             {slide_image_url: String,
//             slide_id: String,
//             }
//         ]
//         pivot_slides: [{
//             slide_id: String,
//             number_of_answers: Number,
//             correct_answer : String
//         }]
//     })
// }
// responseSchema = {
//     presentationId: String,
//     sessions : [
//     session : {
//         sessionId : String (randomly generated by us - UUID),
//         responses : [
//             {response : {
//                 slide_id : String,
//                 username : String,
//                 response : ABCDE (String),
//                 is_correct : Bool
//             }}
//         ]
//     }]
// }

// const api = axios.create({
//     baseURL: 
